/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airlineticketingsystem;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Anood
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
//        resizeAndSetImage();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblmainform = new javax.swing.JLabel();
        btnUserMain = new javax.swing.JToggleButton();
        btnAirline = new javax.swing.JToggleButton();
        btnAdmin = new javax.swing.JButton();
        btnExitAirlineMain2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblmainform.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblmainform.setText("Welcome To SkyTicket!");

        btnUserMain.setBackground(new java.awt.Color(102, 204, 255));
        btnUserMain.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btnUserMain.setForeground(new java.awt.Color(255, 255, 255));
        btnUserMain.setText(" User");
        btnUserMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserMainActionPerformed(evt);
            }
        });

        btnAirline.setBackground(new java.awt.Color(45, 213, 171));
        btnAirline.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btnAirline.setForeground(new java.awt.Color(255, 255, 255));
        btnAirline.setText("Airline");
        btnAirline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAirlineActionPerformed(evt);
            }
        });

        btnAdmin.setBackground(new java.awt.Color(102, 204, 255));
        btnAdmin.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btnAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnAdmin.setText("Admin");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        btnExitAirlineMain2.setBackground(new java.awt.Color(45, 213, 171));
        btnExitAirlineMain2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnExitAirlineMain2.setForeground(new java.awt.Color(255, 255, 255));
        btnExitAirlineMain2.setText("Exit");
        btnExitAirlineMain2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitAirlineMain2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblmainform, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAirline, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(btnUserMain, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(btnAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExitAirlineMain2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblmainform)
                .addGap(50, 50, 50)
                .addComponent(btnUserMain, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btnExitAirlineMain2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnUserMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserMainActionPerformed
        UserMainForm form = new UserMainForm();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnUserMainActionPerformed

    private void btnAirlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAirlineActionPerformed
        AirlineMainForm form = new AirlineMainForm();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAirlineActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        AdminLoginForm form = new AdminLoginForm();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnExitAirlineMain2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitAirlineMain2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitAirlineMain2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JToggleButton btnAirline;
    private javax.swing.JToggleButton btnExitAirlineMain;
    private javax.swing.JToggleButton btnExitAirlineMain1;
    private javax.swing.JToggleButton btnExitAirlineMain2;
    private javax.swing.JToggleButton btnUserMain;
    private javax.swing.JLabel lblmainform;
    // End of variables declaration//GEN-END:variables
}
