/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airlineticketingsystem;

import java.sql.Connection;
import java.sql.Statement;

public class AirlineDashboard extends javax.swing.JFrame {

     ConnectionToDB conn = new ConnectionToDB();
    Connection con = conn.EstablishConnection();
    Statement stmt = null;
    public AirlineDashboard() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAirlineDashboard = new javax.swing.JLabel();
        btnAddFlight = new javax.swing.JButton();
        btnUpdateFlight = new javax.swing.JButton();
        btnCancelFlight = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnAvailableFlights = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAirlineDashboard.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblAirlineDashboard.setText("Welcome Airline!");

        btnAddFlight.setBackground(new java.awt.Color(102, 204, 255));
        btnAddFlight.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btnAddFlight.setForeground(new java.awt.Color(255, 255, 255));
        btnAddFlight.setText("Add a Flight");
        btnAddFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFlightActionPerformed(evt);
            }
        });

        btnUpdateFlight.setBackground(new java.awt.Color(45, 213, 171));
        btnUpdateFlight.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btnUpdateFlight.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateFlight.setText("Update Existing Flight");
        btnUpdateFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateFlightActionPerformed(evt);
            }
        });

        btnCancelFlight.setBackground(new java.awt.Color(45, 213, 171));
        btnCancelFlight.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btnCancelFlight.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelFlight.setText("Cancel Flight");
        btnCancelFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelFlightActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(45, 213, 171));
        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnAvailableFlights.setBackground(new java.awt.Color(102, 204, 255));
        btnAvailableFlights.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btnAvailableFlights.setForeground(new java.awt.Color(255, 255, 255));
        btnAvailableFlights.setText("Show All Available Flights");
        btnAvailableFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvailableFlightsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel2.setText("Select your desired option:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(lblAirlineDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdateFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAvailableFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(193, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblAirlineDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(btnAddFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnUpdateFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnAvailableFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnCancelFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFlightActionPerformed
        AddFlight form = new AddFlight();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddFlightActionPerformed

    private void btnAvailableFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailableFlightsActionPerformed
        AvailableFlights form = new AvailableFlights();
        form.setVisible(true);
    }//GEN-LAST:event_btnAvailableFlightsActionPerformed

    private void btnUpdateFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateFlightActionPerformed
        UpdateFlightByNumber form = new UpdateFlightByNumber();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnUpdateFlightActionPerformed

    private void btnCancelFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelFlightActionPerformed
        CancelFlight form = new CancelFlight();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelFlightActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        AirlineMainForm form = new AirlineMainForm();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFlight;
    private javax.swing.JButton btnAvailableFlights;
    private javax.swing.JButton btnCancelFlight;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdateFlight;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAirlineDashboard;
    // End of variables declaration//GEN-END:variables
}
