/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airlineticketingsystem;

/**
 *
 * @author Talha Shahid
 */
public class AirlineMainForm extends javax.swing.JFrame {

    /**
     * Creates new form AirlineMainForm
     */
    public AirlineMainForm() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRegisterAirlineMain = new javax.swing.JToggleButton();
        btnLoginAirlineMain = new javax.swing.JToggleButton();
        btnExitAirlineMain = new javax.swing.JToggleButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("Welcome To The Airline Dahboard!");

        btnRegisterAirlineMain.setBackground(new java.awt.Color(45, 213, 171));
        btnRegisterAirlineMain.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnRegisterAirlineMain.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterAirlineMain.setText("Register");
        btnRegisterAirlineMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterAirlineMainActionPerformed(evt);
            }
        });

        btnLoginAirlineMain.setBackground(new java.awt.Color(102, 204, 255));
        btnLoginAirlineMain.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnLoginAirlineMain.setForeground(new java.awt.Color(255, 255, 255));
        btnLoginAirlineMain.setText("Login");
        btnLoginAirlineMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginAirlineMainActionPerformed(evt);
            }
        });

        btnExitAirlineMain.setBackground(new java.awt.Color(45, 213, 171));
        btnExitAirlineMain.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnExitAirlineMain.setForeground(new java.awt.Color(255, 255, 255));
        btnExitAirlineMain.setText("Exit");
        btnExitAirlineMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitAirlineMainActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(102, 204, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegisterAirlineMain, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(btnLoginAirlineMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExitAirlineMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(btnRegisterAirlineMain, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnLoginAirlineMain, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnExitAirlineMain, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterAirlineMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterAirlineMainActionPerformed
        AirlineRegistrationForm form = new AirlineRegistrationForm();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegisterAirlineMainActionPerformed

    private void btnLoginAirlineMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginAirlineMainActionPerformed
        AirlineLoginForm form = new AirlineLoginForm();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLoginAirlineMainActionPerformed

    private void btnExitAirlineMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitAirlineMainActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitAirlineMainActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        MainForm form = new MainForm();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JToggleButton btnExitAirlineMain;
    private javax.swing.JToggleButton btnLoginAirlineMain;
    private javax.swing.JToggleButton btnRegisterAirlineMain;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
