/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airlineticketingsystem;


/**
 *
 * @author Talha Shahid
 */
public class UserDashboardForm extends javax.swing.JFrame {

    /**
     * Creates new form UserDashboardForm
     */
    public UserDashboardForm() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBookFlight = new javax.swing.JButton();
        btnSearchFlight = new javax.swing.JButton();
        btnAvailableFlight = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnUserFlights = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("Welcome");

        btnBookFlight.setBackground(new java.awt.Color(102, 204, 255));
        btnBookFlight.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btnBookFlight.setForeground(new java.awt.Color(255, 255, 255));
        btnBookFlight.setText("Book a Flight");
        btnBookFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookFlightActionPerformed(evt);
            }
        });

        btnSearchFlight.setBackground(new java.awt.Color(45, 213, 171));
        btnSearchFlight.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btnSearchFlight.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchFlight.setText("Search Flights");
        btnSearchFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchFlightActionPerformed(evt);
            }
        });

        btnAvailableFlight.setBackground(new java.awt.Color(102, 204, 255));
        btnAvailableFlight.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btnAvailableFlight.setForeground(new java.awt.Color(255, 255, 255));
        btnAvailableFlight.setText("Show Available Flights");
        btnAvailableFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvailableFlightActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(45, 213, 171));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnUserFlights.setBackground(new java.awt.Color(102, 204, 255));
        btnUserFlights.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btnUserFlights.setForeground(new java.awt.Color(255, 255, 255));
        btnUserFlights.setText("Show Your Flights");
        btnUserFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserFlightsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(161, 161, 161)
                            .addComponent(btnBookFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAvailableFlight, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                .addComponent(btnSearchFlight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUserFlights, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)))))
                .addGap(0, 195, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnBookFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearchFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAvailableFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnUserFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchFlightActionPerformed
        SearchFlightForm form = new SearchFlightForm();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSearchFlightActionPerformed

    private void btnAvailableFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailableFlightActionPerformed
        AvailableFlights form = new AvailableFlights();
        form.setVisible(true);
    }//GEN-LAST:event_btnAvailableFlightActionPerformed

    private void btnBookFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookFlightActionPerformed
        BookFlightForm form = new BookFlightForm();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBookFlightActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        UserMainForm form = new UserMainForm();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnUserFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserFlightsActionPerformed
        UserFlights flights = new UserFlights();
        flights.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnUserFlightsActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvailableFlight;
    private javax.swing.JButton btnBookFlight;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSearchFlight;
    private javax.swing.JButton btnUserFlights;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
