package airlineticketingsystem;

import java.sql.*;
import javax.swing.JOptionPane;

public class UserRegistrationForm extends javax.swing.JFrame {

    /**
     * Creates new form UserRegistrationForm
     */
    public UserRegistrationForm() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
    }

    class UserRegisterClass {

        ConnectionToDB conn = new ConnectionToDB();
        Connection con = conn.EstablishConnection();
        Statement stmt = null;
        UserRegistrationForm form;

        public UserRegisterClass(UserRegistrationForm form) {
            this.form = form;
        }

        public void addUser(String name, String email, String password, String phoneNumber) {
            String registerQuery = "insert into User(UserName,Email,Password,PhoneNumber) values ('" + name + "','" + email + "','" + password + "','" + phoneNumber + "')";
            try {
                stmt = con.createStatement();
                int res = stmt.executeUpdate(registerQuery);
                if (res < 0) {
                    JOptionPane.showMessageDialog(null, "Error!");
                } else {
                    JOptionPane.showMessageDialog(null, "Registered!");
                    UserLoginForm loginForm = new UserLoginForm();
                    loginForm.setVisible(true);
                    form.setVisible(false); // Hide the registration form
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhnum = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhNum = new javax.swing.JTextField();
        pwdUser = new javax.swing.JPasswordField();
        lblUseRegForm = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(48, 109, 147));
        setMinimumSize(new java.awt.Dimension(650, 700));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 213, 171), 2));

        lblName.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 0, 102));
        lblName.setText("Name:");

        lblEmail.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 0, 102));
        lblEmail.setText("Email:");

        lblPhnum.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        lblPhnum.setForeground(new java.awt.Color(0, 0, 102));
        lblPhnum.setText("Phone Number:");

        lblPass.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        lblPass.setForeground(new java.awt.Color(0, 0, 102));
        lblPass.setText("Password:");

        txtName.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 255), 2));

        txtEmail.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 255), 2));

        txtPhNum.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtPhNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 255), 2));
        txtPhNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhNumActionPerformed(evt);
            }
        });

        pwdUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 255), 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pwdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhNum, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEmail)
                                    .addComponent(lblName))
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(lblPhnum)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPass, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPhnum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhNum, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pwdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(130, 130, 403, 420);

        lblUseRegForm.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblUseRegForm.setForeground(new java.awt.Color(0, 0, 102));
        lblUseRegForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUseRegForm.setText("User Registration Form");
        getContentPane().add(lblUseRegForm);
        lblUseRegForm.setBounds(130, 40, 412, 70);

        btnBack.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(102, 204, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(500, 650, 100, 30);

        btnRegister.setBackground(new java.awt.Color(45, 213, 171));
        btnRegister.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister);
        btnRegister.setBounds(160, 560, 360, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPhNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhNumActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        UserMainForm form = new UserMainForm();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        String name = txtName.getText();
        String email = txtEmail.getText();
        String password = String.valueOf(pwdUser.getPassword());
        String phoneNumber = txtPhNum.getText();

        if (!name.matches("[a-zA-Z]+")) {
            JOptionPane.showMessageDialog(this, "Invalid name! Please enter only alphabets for your name.");
            return;
        }

        if (!email.contains("@")) {
            JOptionPane.showMessageDialog(this, "Invalid email! Please enter a valid email address containing '@'.");
            return;
        }

        UserRegisterClass register = new UserRegisterClass(this); // Pass the form reference
        register.addUser(name, email, password, phoneNumber);
    }//GEN-LAST:event_btnRegisterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPhnum;
    private javax.swing.JLabel lblUseRegForm;
    private javax.swing.JPasswordField pwdUser;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhNum;
    // End of variables declaration//GEN-END:variables
}
