/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airlineticketingsystem;

/**
 *
 * @author Anood
 */
public class UserMainForm extends javax.swing.JFrame {

    /**
     * Creates new form UserMainForm
     */
    public UserMainForm() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRegisterUserMain = new javax.swing.JToggleButton();
        btnLoginUserMain = new javax.swing.JToggleButton();
        btnExitUserMain = new javax.swing.JToggleButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("Welcome!");

        btnRegisterUserMain.setBackground(new java.awt.Color(102, 204, 255));
        btnRegisterUserMain.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btnRegisterUserMain.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterUserMain.setText("Register");
        btnRegisterUserMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterUserMainActionPerformed(evt);
            }
        });

        btnLoginUserMain.setBackground(new java.awt.Color(45, 213, 171));
        btnLoginUserMain.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btnLoginUserMain.setForeground(new java.awt.Color(255, 255, 255));
        btnLoginUserMain.setText("Login");
        btnLoginUserMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginUserMainActionPerformed(evt);
            }
        });

        btnExitUserMain.setBackground(new java.awt.Color(102, 204, 255));
        btnExitUserMain.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btnExitUserMain.setForeground(new java.awt.Color(255, 255, 255));
        btnExitUserMain.setText("Exit");
        btnExitUserMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitUserMainActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(102, 204, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExitUserMain, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoginUserMain, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(172, 172, 172)
                            .addComponent(btnRegisterUserMain, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(199, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(btnRegisterUserMain, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnLoginUserMain, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnExitUserMain, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterUserMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterUserMainActionPerformed
        UserRegistrationForm form = new UserRegistrationForm();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegisterUserMainActionPerformed

    private void btnLoginUserMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginUserMainActionPerformed
       UserLoginForm form = new UserLoginForm();
       form.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnLoginUserMainActionPerformed

    private void btnExitUserMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitUserMainActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitUserMainActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        MainForm form = new MainForm();
        form.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JToggleButton btnExitUserMain;
    private javax.swing.JToggleButton btnLoginUserMain;
    private javax.swing.JToggleButton btnRegisterUserMain;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
