/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airlineticketingsystem;

import airlineticketingsystem.Admin.RemoveUser;



/**
 *
 * @author Talha Shahid
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdminDashboard = new javax.swing.JLabel();
        btnRemoveAirAdminDash = new javax.swing.JButton();
        btnViewFlightAdminDash = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnRemoveUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAdminDashboard.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblAdminDashboard.setText("Welcome Admin!");

        btnRemoveAirAdminDash.setBackground(new java.awt.Color(45, 213, 171));
        btnRemoveAirAdminDash.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btnRemoveAirAdminDash.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveAirAdminDash.setText("Remove Airlines");
        btnRemoveAirAdminDash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveAirAdminDashActionPerformed(evt);
            }
        });

        btnViewFlightAdminDash.setBackground(new java.awt.Color(45, 213, 171));
        btnViewFlightAdminDash.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btnViewFlightAdminDash.setForeground(new java.awt.Color(255, 255, 255));
        btnViewFlightAdminDash.setText("View Flights");
        btnViewFlightAdminDash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFlightAdminDashActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(102, 204, 255));
        btnLogout.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnRemoveUser.setBackground(new java.awt.Color(102, 204, 255));
        btnRemoveUser.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btnRemoveUser.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveUser.setText("Remove User");
        btnRemoveUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblAdminDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(401, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRemoveAirAdminDash, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(btnViewFlightAdminDash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemoveUser, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblAdminDashboard)
                .addGap(73, 73, 73)
                .addComponent(btnRemoveAirAdminDash, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnRemoveUser, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnViewFlightAdminDash, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewFlightAdminDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFlightAdminDashActionPerformed
        AvailableFlights flights = new AvailableFlights();
        flights.setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_btnViewFlightAdminDashActionPerformed

    private void btnRemoveAirAdminDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveAirAdminDashActionPerformed
        RemoveAirline airline = new RemoveAirline();
        airline.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRemoveAirAdminDashActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        MainForm form = new MainForm();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnRemoveUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveUserActionPerformed
       RemoveUser user = new RemoveUser();
       user.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnRemoveUserActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRemoveAirAdminDash;
    private javax.swing.JButton btnRemoveUser;
    private javax.swing.JButton btnViewFlightAdminDash;
    private javax.swing.JLabel lblAdminDashboard;
    // End of variables declaration//GEN-END:variables
}
